### ISSUE TITLE
Converting Markdown from a response model into Markup

### ISSUE THREAD

**Issue by Cyberlane** [jchannon/Nancy.ViewEngines.Markdown#2]
This is a tough one to explain without examples, so here goes...

I want to be able to do this within the module:

``` csharp
Get["/"] = _ => {
  var model = new PageModel {
    Title = "Home",
    Content = ReadFile("Content/pages/home.md")
  };
  return MarkdownView<PageModel>("default", model, x => { x.Content });
};
```

Now keep in mind that Content in this point is in fact still markdown code, and nothing has changed it!

Now within a JSON request, I want the following returned:

``` json
{
  Title: "Home",
  Content: "#markdown goes here"
}
```

The content within that response is also still markdown.

Now when I have a razor page doing something like this:

``` cshtml
@inherits Nancy.ViewEngines.Razor.NancyRazorViewBase<SimpleTest.Models.PageModel>
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@Model.Title</title>
</head>
<body>
  @Model.Content
</body>
</html>
```

All of the properties selected in the selector at the end of the MarkdownView will be converted into HTML for text/html requests.

**Comment by thecodejunkie** [comment]
Spoke to @Cyberlane about this. It's not related to the markdown view engine. 

Should be closed :closed_lock_with_key:
